### ISSUE TITLE
Map View is Buggy

### ISSUE THREAD

**Issue by mistermichaelll** [Haikoitoh/CityVista#1]
Howdy! I saw your project on Reddit and it's super cool! 

Just wanted to point out that the map view is a bit buggy on my system in both Safari and Chrome:

<img width="947" alt="Screenshot 2024-02-07 at 6 13 47 PM" src="https://github.com/Haikoitoh/CityVista/assets/33233019/50532643-a425-45e8-b638-c158a47b09c3">

**Comment by Haikoitoh** [comment]
Thanks for pointing it out ! I will look into it.

**Comment by Haikoitoh** [comment]
The map issue has been solved. 
Keeping the issue open until you confirm that its solved on your end.

**Comment by mistermichaelll** [comment]
Looks good!
